# Assignment 0

### <span style="color:chocolate"> Submission requirements </span>

Your work will not be graded if your notebook doesn't include output. In other words, <span style="color:red"> make sure to rerun your notebook before submitting to Gradescope </span> (Note: if you are using Google Colab: go to Edit > Notebook Settings  and uncheck Omit code cell output when saving this notebook, otherwise the output is not printed).

Additional points may be deducted if these requirements are not met:

    
* Comment your code;
* Each graph should have a title, labels for each axis, and (if needed) a legend. Each graph should be understandable on its own;
* Try and minimize the use of the global namespace (meaning, keep things inside functions).
---

### Import libraries

In [1]:
import numpy as np
np.random.seed(seed=1)

---
### <span style="color:chocolate">Exercise 1:</span> Homogenous data types (10 points)

1. Create a numpy array (my_array1) containing only integer values. Print the shape of the array and the type of its elements;
2. Create another numpy array (my_array2) containing a mix of integer and string values. Print the shape of the array and the type of its elements. What explains the datatype of the array?

In [2]:
my_array1 = np.array([1, 3, 5, 7, 9, 11])
print("Shape of my_array1: ", my_array1.shape)
print("Datatype of my_array1: ", my_array1.dtype)

my_array2 = np.array([1, "USS Enterprise", 2, "USS Defiant", 3, "USS Voyager", 4, "USS Discovery"])
print("Shape of my_array2: ", my_array2.shape)

#Prints the data type of the array. The datatype is unicode of the length of the longest string because we have a string in the array. This allows numpy to standardize all the elements as unicode string for efficiency of processing.
print("Datatype of my_array2: ", my_array2.dtype)

Shape of my_array1:  (6,)
Datatype of my_array1:  int64
Shape of my_array2:  (8,)
Datatype of my_array2:  <U21


---
#### <span style="color:chocolate">Exercise 2:</span> The size attribute (10 points)

Create a numpy array (my_array3) and print its shape, size, and data type. What does size represent?

In [3]:
my_array3 = np.array([[11,12,13],[21,22,23]])
print("Shape of my_array3: ", my_array3.shape)

# Size is the total number of individual elements.
print("Size of my_array3: ", my_array3.size)

print("Datatype of my_array3: ", my_array3.dtype)

Shape of my_array3:  (2, 3)
Size of my_array3:  6
Datatype of my_array3:  int64


---
#### <span style="color:chocolate">Exercise 3:</span> Tabular data layout (10 points)

Create a tabular data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:
* the first input is num_samples, and
* the second input is num_features. 

Print the shape of the array.

In [4]:
# already defined first and second inputs
num_samples = 100
num_features = 17

tabular_data = np.random.random((num_samples, num_features))
print("Shape of tabular_data: ", tabular_data.shape)

Shape of tabular_data:  (100, 17)


---
#### <span style="color:chocolate">Exercise 4:</span> Image data layout (10 points)

Create an image data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:

* the first input is num_images;
* the second input is num_rows;
* the third input is num_cols;
* the fourth input is num_channels.

Print the shape of the array.

In [5]:
# already defined inputs
num_images = 100
num_rows = 256
num_cols = 256
num_channels = 3 #(RGB)

image_data = np.random.random((num_images, num_rows, num_cols, num_channels))

#The shape of the data is the number of elements in each dimension
print("Shape of image_data: ", image_data.shape)

Shape of image_data:  (100, 256, 256, 3)


---
#### <span style="color:chocolate">Exercise 5: </span>Mathematical operations on numpy arrays (15 points)

Create a (3, 2) numpy array (you can name it my_array4) containing only integer values. Perform the following tasks:

1. Print the shape of the array;
2. Print the sum of all elements (hint: the axis argument is set to None);
3. Print the sum of all elements by column;
3. Print the sum of all elements by row and change the type of the resulting array elements to float;
5. Print the first row of the array;
6. Print the second row of the array;
7. Select the element at position (1, 0);
8. Modify the element at position (2, 1) by setting its value to 10 and print the array again;
9. Loop over all the elements in the array. Print the output.

In [6]:
my_array4 = np.array([[1, 3], [2, 4], [10, 20]])
print("Shape of my_array4: ", my_array4.shape)
print("Sum of all elements of my_array4: ", my_array4.sum(axis=None))
print("Sum of all elements by column of my_array4: ", my_array4.sum(axis=0))
print("Sum of all elements by row as array of my_array4: ", my_array4.sum(axis=1).astype(float))
print("First row of my_array4: ", my_array4[0])
print("Second row of my_array4: ", my_array4[1])
print("Element at position (1, 0) of my_array4: ", my_array4[1, 0])

my_array4[2, 1] = 10
print("Modified element at position (2, 1) and update of my_array4:\n", my_array4)

# There isn't a requirement that I print out in a specific order, so I use nditer for smplicity
print("All elements of my_array4:")
for x in np.nditer(my_array4):
    print(x)

Shape of my_array4:  (3, 2)
Sum of all elements of my_array4:  40
Sum of all elements by column of my_array4:  [13 27]
Sum of all elements by row as array of my_array4:  [ 4.  6. 30.]
First row of my_array4:  [1 3]
Second row of my_array4:  [2 4]
Element at position (1, 0) of my_array4:  2
Modified element at position (2, 1) and update of my_array4:
 [[ 1  3]
 [ 2  4]
 [10 10]]
All elements of my_array4:
1
3
2
4
10
10


You can find more examples here: https://numpy.org/doc/stable/reference/routines.math.html

---
#### <span style="color:chocolate">Exercise 6:</span> Create arrays (15 points)

1. Create and print a (3,2) numpy array of pixel values between 0 and 1.
2. Create and print a (27,) numpy array representing years from 1991 to 2017
3. Create and print a (3, 5, 10) numpy array of zeros
4. Create and print a (3, 5, 10) numpy array of ones
5. Create and print an array with a constant value (let's say 5) using np.ones()
6. Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.


In [7]:
pixels_array = np.random.random((3, 2))
print("pixels_array:\n", pixels_array)

# need to use 2018 to get 27 elements ebcause stop is eclusive
years_array = np.arange(1991, 2018)
print("years_array:\n", years_array)

zeroes_array = np.zeros((3, 5, 10))
print("zeroes_array:\n", zeroes_array)

ones_array = np.ones((3, 5, 10))
print("ones_array:\n", ones_array)

five_array = np.ones(4) * 5
print("five_array: ", five_array)

rng = np.random.default_rng()
normal_dist_array = rng.standard_normal(10)
print("normal_dist_arry: ", normal_dist_array)

pixels_array:
 [[0.28999571 0.50818013]
 [0.47655793 0.57281228]
 [0.53403895 0.66869277]]
years_array:
 [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
zeroes_array:
 [[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
ones_array:
 [[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1

---
#### <span style="color:chocolate">Exercise 7:</span> Reshape arrays (10 points)

Consider the following array:

In [8]:
years = np.arange(1991, 2018, 1)
print(years.shape)

(27,)


Perform the following operations on this array:
    
1. Create 3 nested arrays, each of size (3, 3). Call this array years_3d (Hint: use np.reshape());
2. Convert the years_3d array to a flat 1D array. Call this array years_1d (Hint: use np.flatten());
3. Add a new dimension (axis=0) to the years_1d array. Call this array years_2d (Hint: use np.expand_dims());
4. Remove the first axis from years_2d array. Call this array years_1d (Hint: use np.squeeze()).

For each exercise print the array and its shape.

In [9]:
years_3d = years.reshape(3, 3, 3)
print("years_3d:\n", years_3d)
print("Shape of years_3d:", years_3d.shape)

years_1d = years_3d.flatten()
print("years_1d:\n", years_1d)
print("Shape of years_1d:", years_1d.shape)

years_2d = np.expand_dims(years_1d, axis=0)
print("years_2d:\n", years_2d)
print("Shape of years_2d:", years_2d.shape)

years_1d = np.squeeze(years_2d)
print("years_1d (updated):\n", years_1d)
print("Shape of years_1d (updated):", years_1d.shape)

years_3d:
 [[[1991 1992 1993]
  [1994 1995 1996]
  [1997 1998 1999]]

 [[2000 2001 2002]
  [2003 2004 2005]
  [2006 2007 2008]]

 [[2009 2010 2011]
  [2012 2013 2014]
  [2015 2016 2017]]]
Shape of years_3d: (3, 3, 3)
years_1d:
 [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
Shape of years_1d: (27,)
years_2d:
 [[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
  2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]]
Shape of years_2d: (1, 27)
years_1d (updated):
 [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
Shape of years_1d (updated): (27,)


---
#### <span style="color:chocolate">Exercise 8:</span> Joining arrays (10 points)

Provide 8 examples that use the methods <span style="color:cornflowerBlue">np.concatenate()</span> and <span style="color:cornflowerBlue">np.stack()</span>. Note: create 4 examples using each method.

In [10]:
input_1x2_a_array = np.array([1, 2])
input_1x2_b_array = np.array([3, 4])
input_1x2_c_array = np.array([5, 6])
input_2x2_a_array = np.array([[1, 2], [3, 4]])
input_2x2_b_array = np.array([[5, 6], [7, 8]])

# Concatenate 2 1D arrays
c1_array = np.concatenate((input_1x2_a_array, input_1x2_b_array))
print("c1_array:\n", c1_array)

# Concatenate vertically (2D array)
c2_array = np.concatenate((input_2x2_a_array, input_2x2_b_array), axis=0)
print("c2_array:\n", c2_array)

# Concatenate horizontally (2D array)
c3_array = np.concatenate((input_2x2_a_array, input_2x2_b_array), axis=1)
print("c3_array:\n", c3_array)

# Concatenate 3 1D arrays
c4_array = np.concatenate((input_1x2_a_array, input_1x2_b_array, input_1x2_c_array))
print("c4_array:\n", c4_array)

# Create stacks as with layers
s1_stack = np.stack((input_2x2_a_array, input_2x2_b_array), axis=0)
print("s1_stack:\n", s1_stack)

# Create stacks with alternating rows
s2_stack = np.stack((input_2x2_a_array, input_2x2_b_array), axis=1)
print("s2_stack:\n", s2_stack)

# Create stacks with alternating columns
s3_stack = np.stack((input_2x2_a_array, input_2x2_b_array), axis=2)
print("s3_stack:\n", s3_stack)

# Create 2D arrays from 2 1D arrays
s4_stack = np.stack((input_1x2_a_array, input_1x2_b_array), axis=0)
print("s4_stack:\n", s4_stack)

c1_array:
 [1 2 3 4]
c2_array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
c3_array:
 [[1 2 5 6]
 [3 4 7 8]]
c4_array:
 [1 2 3 4 5 6]
s1_stack:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
s2_stack:
 [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
s3_stack:
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
s4_stack:
 [[1 2]
 [3 4]]


---
#### <span style="color:chocolate">Numpy broadcasting</span> 

The term broadcasting describes how NumPy treats arrays during arithmetic operations. You can find more here:  https://numpy.org/doc/stable/user/basics.broadcasting.html

In [11]:
# multiplying an array with a scalar
years = np.arange(1991, 2018, 1)
years * 1

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])

In [12]:
# adding a scalar
years + 2

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019])

In [13]:
# many arithmetic operations are applied element wise on a pair of arrays
a = np.arange(3)
print('Array a:', a)
b = np.arange(3)
print('Array b:', b)
print('Sum of a and b:', a+b)

Array a: [0 1 2]
Array b: [0 1 2]
Sum of a and b: [0 2 4]


In [14]:
# another example
a = np.ones((3, 3))
print('Array a:', a)
b = np.arange(3)
print('\nArray b:', b)
print('\nSum of a and b:', a+b)

Array a: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array b: [0 1 2]

Sum of a and b: [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


---
#### <span style="color:chocolate">Exercise 9:</span> Numpy array standardization (10 points)

Consider the following (10, 4) array:

In [15]:
my_array = np.random.random((10, 4))
print('my_array shape: ', my_array.shape)
my_array

my_array shape:  (10, 4)


array([[8.63713042e-01, 1.01159076e-01, 7.08455444e-01, 5.29867591e-01],
       [8.56836322e-01, 1.35555227e-01, 3.39596319e-01, 5.05095363e-01],
       [2.70880657e-01, 1.01195812e-01, 4.17556557e-01, 9.48341859e-01],
       [2.15631802e-01, 1.45999378e-01, 5.31221554e-01, 2.37281923e-01],
       [8.72005547e-01, 9.89537574e-01, 9.44649530e-01, 2.59047822e-02],
       [2.41036029e-01, 2.09232762e-01, 6.91936843e-01, 7.02465192e-01],
       [5.92360703e-01, 2.85496978e-01, 9.10061264e-02, 4.74607622e-01],
       [2.44213847e-01, 3.08055169e-02, 6.55060658e-01, 9.80750478e-04],
       [4.46020788e-01, 9.63664756e-01, 3.86439740e-01, 4.09421652e-01],
       [2.32061314e-02, 3.67139198e-02, 3.02058733e-01, 9.58056443e-01]])

Peform the following operations on this array:
1. Compute and print the mean and std for each column (note: set keepdims=True for proper broadcasting).
2. Standardize and print the array and its shape using the mean and std you computed above.

In [16]:
my_array_mean = my_array.mean(axis=0, keepdims=True)
my_array_std = my_array.std(axis=0, keepdims=True)
print("Column means of my_array: ", my_array_mean)
print("Column std of my_array: ", my_array_std)

standardized_array = (my_array - my_array_mean) / my_array_std
print("standardized_array:\n", standardized_array)
print("Shape of standardized_array: ", standardized_array.shape)

Column means of my_array:  [[0.46259049 0.2999361  0.50679815 0.47920232]]
Column std of my_array:  [[0.29810053 0.34582745 0.23546592 0.31623842]]
standardized_array:
 [[ 1.34559493 -0.57478671  0.85641817  0.16021227]
 [ 1.32252646 -0.47532627 -0.7100893   0.08187824]
 [-0.64310464 -0.57468048 -0.37900004  1.48349952]
 [-0.82844096 -0.4451258   0.10372373 -0.76499369]
 [ 1.37341274  1.99406225  1.85951061 -1.43340439]
 [-0.74322062 -0.26227917  0.78626534  0.70599542]
 [ 0.43532367 -0.04175239 -1.76582676 -0.01452921]
 [-0.7325604  -0.77822214  0.6296559  -1.51221844]
 [-0.05558427  1.91924801 -0.51115002 -0.22065841]
 [-1.47394693 -0.76113731 -0.86950764  1.5142187 ]]
Shape of standardized_array:  (10, 4)


----
#### <span style="color:chocolate">Additional practice question</span> (not graded)

Consider the following image:

In [17]:
my_image = np.arange(0, 1, 0.04).reshape(5,5)
print(my_image)
my_image.shape

[[0.   0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]


(5, 5)

Perform the following operations on this image (do not overwrite the original image):

1. Crop by using a border of size 1;
2. Crop by removing:
    * the first and the last two rows, and
    * the first and the last two columns;
3. Reverse the column order;
4. set to 0.5 elements divizible by 2.

In [18]:
# YOUR CODE HERE